import random
import matplotlib.pyplot as plt
import numpy as np
from Bio import Align
from Bio.Align import substitution_matrices

seq1 = ("NTMLDAAVVSLTSQLVSDIVPTENSNFDSTYNFTALMGCLGSSCNSKRSAISDLLYNKVKIADPGFMDSYQKCIDSQWGGNIRDLICTQVFNGIAVLPPIVSPGMQALYTSL"
        "LVGAVASSGYTFGITSVGVIPFATQLQFRLNGIGVTTQVLVDNQKLIASSFNNALNQIQKGFDATNSALSKIQAVINQHATQLQTLVLQLGNTFGAISSSINIIFSRLEGLE"
        "ADAEVDRLISGRMVVLNTYVTQLLVQASRIKAQSDLALQKINECVKSQTLRNEFCGNGTHVLSVPQLAPNGIMFIHYSYTPTQYATVQTAAGLCFNGTGYAPRNGLFILPNN"
        "SNFWYFTQANFYNPVNISNSNTQVLESCSVNYTTVNYTILSPQEPLYNNFDEEFNKFYKNLSSVFNNTFNPGAFNFSTVELQSEIATLNEVVQQLNKSFIDLKQMNVYEQTI"
        "KWPWYVWLAMIAGLVGLALAVVMLLCMTNCCSCFKGMCSCRHCYYDEIEDVYPAVRVHNKRTA")

seq2 = ("MFVFLVLLPLVSSQCVNLTTRTQLPPANTNSFTRGVYYPDKVFRSSVLHSTQDLFLPFFSNVTWFHAIHVSGTNGTKRFDNPVLPFNDGVYFASTEKSNIIRGWIFGTTLDS"
        "KTQSLLIVNNATNVVIKVCEFQFCNDPFLGVYYHKNNKSWMESEFRVYSSANNCTFEYVSQPFLMDLEGKQGNFKNLREFVFKNIDGYFKIYSKHTPINLVRDLPQGFSALE"
        "PLVDLPIGINITRFQTLLALHRSYLTPGDSSSGWTAGAAAYYVGYLQPRTFLLKYNENGTITDAVDCALDPLSETKCTLKSFTVEKGIYQTSNFRVQPTESIVRFPNITNLC"
        "PFGEVFNATRFASVYAWNRKRISNCVADYSVLYNSASFSTFKCYGVSPTKLNDLCFTNVYADSFVIRGDEVRQIAPGQTGKIADYNYKLPDDFTGCVIAWNSNNLDSKVGGN"
        "YNYLYRLFRKSNLKPFERDISTEIYQAGSTPCNGVEGFNCYFPLQSYGFQPTNGVGYQPYRVVVLSFELLHAPATVCGPKKSTNLVKNKCVNFNFNGLTGTGVLTESNKKFL"
        "PFQQFGRDIADTTDAVRDPQTLEILDITPCSFGGVSVITPGTNTSNQVAVLYQDVNCTEVPVAIHADQLTPTWRVYSTGSNVFQTRAGCLIGAEHVNNSYECDIPIGAGICA"
        "SYQTQTNSPRRARSVASQSIIAYTMSLGAENSVAYSNNSIAIPTNFTISVTTEILPVSMTKTSVDCTMYICGDSTECSNLLLQYGSFCTQLNRALTGIAVEQDKNTQEVFAQ"
        "VKQIYKTPPIKDFGGFNFSQILPDPSKPSKRSFIEDLLFNKVTLADAGFIKQYGDCLGDIAARDLICAQKFNGLTVLPPLLTDEMIAQYTSALLAGTITSGWTFGAGAALQI"
        "PFAMQMAYRFNGIGVTQNVLYENQKLIANQFNSAIGKIQDSLSSTASALGKLQDVVNQNAQALNTLVKQLSSNFGAISSVLNDILSRLDKVEAEVQIDRLITGRLQSLQTYV"
        "TQQLIRAAEIRASANLAATKMSECVLGQSKRVDFCGKGYHLMSFPQSAPHGVVFLHVTYVPAQEKNFTTAPAICHDGKAHFPREGVFVSNGTHWFVTQRNFYEPQIITTDNT"
        "FVSGNCDVVIGIVNNTVYDPLQPELDSFKEELDKYFKNHTSPDVDLGDISGINASVVNIQKEIDRLNEVAKNLNESLIDLQELGKYEQYIKWPWYIWLGFIAGLIAIVMVTI"
        "MLCCMTSCCSCLKGCCSCGSCCKFDEDDSEPVLKGVKLHYT")

aligner = Align.PairwiseAligner()
aligner.mode = 'local' 
aligner.substitution_matrix = substitution_matrices.load("BLOSUM62") 

alignments = aligner.align(seq1, seq2)
print(f"Score with defaults: {alignments.score}")

aligner.open_gap_score = -10.0
aligner.extend_gap_score = -0.5
alignments_adjusted = aligner.align(seq1, seq2)
print(f"Score with Water parameters: {alignments_adjusted.score}")

observed_score = 1143.5 
n = 100 
random_scores = []
seq1_list = list(seq1) 

print("Permutations...")
for i in range(n):
    random.shuffle(seq1_list)
    shuffled_seq = "".join(seq1_list)
    

    score = aligner.score(shuffled_seq, seq2)
    random_scores.append(score)

s_perm_ge_s = sum(1 for s in random_scores if s >= observed_score)
p_value = s_perm_ge_s / n

print(f"P-value: {p_value}")

plt.hist(random_scores, bins=20, color='blue', alpha=0.7, label='Random Scores')
plt.axvline(observed_score, color='red', linestyle='dashed', linewidth=2, label='Observed Score')
plt.title('Distribution of Random Alignment Scores')
plt.xlabel('Score')
plt.ylabel('Frequency')
plt.legend()
plt.show()